package views;

import gals.LexicalError;
import gals.Lexico;
import gals.SemanticError;
import gals.Semantico;
import gals.Sintatico;
import gals.SyntaticError;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.text.BadLocationException;

public class Principal extends javax.swing.JFrame {

    String arquivo_salvar;

    public Principal() {
        initComponents();
        ativarBotoesSalvar(false);
        btAnalise.setEnabled(true);
        arquivo_salvar = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAbrir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btSalvarComo = new javax.swing.JButton();
        btAnalise = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        retornoAnalise = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        editorCodigo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador (Beta)");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/open.png"))); // NOI18N
        btAbrir.setToolTipText("Abrir");
        btAbrir.setMaximumSize(new java.awt.Dimension(50, 50));
        btAbrir.setPreferredSize(new java.awt.Dimension(50, 50));
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(btAbrir);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/salvar.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.setMaximumSize(new java.awt.Dimension(50, 50));
        btSalvar.setPreferredSize(new java.awt.Dimension(50, 50));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar);

        btSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/salvar_como.png"))); // NOI18N
        btSalvarComo.setToolTipText("Salvar como...");
        btSalvarComo.setMaximumSize(new java.awt.Dimension(50, 50));
        btSalvarComo.setPreferredSize(new java.awt.Dimension(50, 50));
        btSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarComoActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvarComo);

        btAnalise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/verificar.png"))); // NOI18N
        btAnalise.setToolTipText("Analisar");
        btAnalise.setMaximumSize(new java.awt.Dimension(50, 50));
        btAnalise.setPreferredSize(new java.awt.Dimension(50, 50));
        btAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnaliseActionPerformed(evt);
            }
        });
        jPanel1.add(btAnalise);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setToolTipText("Código");
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(183, 130));
        jPanel5.setLayout(new java.awt.BorderLayout());

        retornoAnalise.setEditable(false);
        retornoAnalise.setColumns(20);
        retornoAnalise.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        retornoAnalise.setRows(5);
        retornoAnalise.setMinimumSize(new java.awt.Dimension(4, 200));
        jScrollPane1.setViewportView(retornoAnalise);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        editorCodigo.setColumns(20);
        editorCodigo.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        editorCodigo.setRows(5);
        editorCodigo.setText("/*\nCompilador v1 - Beta\n*/\nprogram {\n\tvoid main(){\n\n\t}\t\t\t\t\n}");
        editorCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editorCodigoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(editorCodigo);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarComoActionPerformed

        JFileChooser seletor_arquivo = new JFileChooser();
        if (seletor_arquivo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            arquivo_salvar = seletor_arquivo.getSelectedFile().getAbsolutePath();
        }

        if (!arquivo_salvar.equals("")) {
            try {
                BufferedWriter arquivo = new BufferedWriter(new FileWriter(arquivo_salvar));
                arquivo.flush();
                arquivo.write(editorCodigo.getText());
                arquivo.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSalvarComoActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        JFileChooser seletor_arquivo = new JFileChooser();
        int aux = seletor_arquivo.showOpenDialog(this);

        if (aux == JFileChooser.APPROVE_OPTION) {
            try {
                arquivo_salvar = seletor_arquivo.getSelectedFile().getAbsolutePath();
                File arquivo = new File(arquivo_salvar);
                editorCodigo.setText("");
                editorCodigo.setText(new String(Files.readAllBytes(arquivo.toPath())));
                btAnalise.setEnabled(true);
            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btAbrirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (arquivo_salvar.equals("")) {
            JFileChooser seletor_arquivo = new JFileChooser();
            if (seletor_arquivo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                arquivo_salvar = seletor_arquivo.getSelectedFile().getAbsolutePath();
            }

        }
        if (!arquivo_salvar.equals("")) {
            try {
                BufferedWriter arquivo = new BufferedWriter(new FileWriter(arquivo_salvar));
                arquivo.flush();
                arquivo.write(editorCodigo.getText());
                arquivo.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void editorCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editorCodigoKeyReleased
        ativarBotoesSalvar(true);
    }//GEN-LAST:event_editorCodigoKeyReleased

    private void btAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnaliseActionPerformed

        try {
            Lexico lex = new Lexico(editorCodigo.getText());
            Sintatico sin = new Sintatico();
            Semantico sem = new Semantico();
            sin.parse(lex, sem);
            retornoAnalise.setForeground(Color.BLUE);
            retornoAnalise.setText("NENHUM PROBLEMA ENCONTRADO");
        } catch (LexicalError | SyntaticError | SemanticError ex) {
            try {
                int pos;

                if (ex.getPosition() < 20) {
                    pos = ex.getPosition();
                } else {
                    pos = 20;
                }

                retornoAnalise.setForeground(Color.red);
                retornoAnalise.setText(ex.getMessage());
                retornoAnalise.append("\n-----------------------------------------------------------------------");
                retornoAnalise.append("\n" + "Último trecho válido: \n"
                        + editorCodigo.getText(ex.getPosition() - pos, pos));
                retornoAnalise.append("\n-----------------------------------------------------------------------");
            } catch (BadLocationException ex1) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btAnaliseActionPerformed

    private void ativarBotoesSalvar(boolean ativar) {
        btSalvar.setEnabled(ativar);
        btSalvarComo.setEnabled(ativar);
        btAnalise.setEnabled(ativar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btAnalise;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvarComo;
    private javax.swing.JTextArea editorCodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea retornoAnalise;
    // End of variables declaration//GEN-END:variables
}
